import pandas as pd

# --- Configuration ---
# Path to the candidate file generated by your main script
CANDIDATES_CSV = "exoplanet_candidates_results/candidates.csv"

# Path to the CSV file you downloaded from the NASA Exoplanet Archive
KNOWN_HOSTS_CSV = "known_planet_hosts.csv"

# Name for the final, filtered output file
FINAL_CANDIDATES_FILE = "new_unvetted_candidates.csv"


# --- Main Filtering Logic ---
try:
    # Read the candidates generated by your script
    candidates_df = pd.read_csv(CANDIDATES_CSV)
    print(f"Read {len(candidates_df)} total candidates from '{CANDIDATES_CSV}'.")

    # Read the list of known exoplanet hosts you downloaded
    known_hosts_df = pd.read_csv(KNOWN_HOSTS_CSV)

    # Get a unique list of TIC IDs from the known hosts file.
    # The column name from the archive is 'tic_id'.
    known_tics = known_hosts_df['tic_id'].dropna().unique()
    print(f"Read {len(known_tics)} unique known exoplanet hosts from '{KNOWN_HOSTS_CSV}'.")

    # Filter your candidates: keep only the rows where the 'tic_id' is NOT in the list of known TICs.
    # The '~' symbol inverts the selection.
    new_candidates_df = candidates_df[~candidates_df['tic_id'].isin(known_tics)]
    print(f"Found {len(new_candidates_df)} new, unvetted candidates.")

    # Save the purely new candidates to a new file
    if not new_candidates_df.empty:
        new_candidates_df.to_csv(FINAL_CANDIDATES_FILE, index=False)
        print(f"Successfully saved new candidates to '{FINAL_CANDIDATES_FILE}'.")
    else:
        print("No new candidates were found after filtering.")

except FileNotFoundError as e:
    print(f"Error: Could not find a required file. Please check your file paths. Details: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")